version: '3.3'

services:
  app:
    image: matomo:3.13.5
    restart: always
    volumes:
      - ./matomo-data:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mariadb:10.4.12
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - matomo.env